### PR TITLE
Update Icon path

### PR DESCRIPTION
**Pull request by Klumbumbus**
the icon was removed in JOSM in https://josm.openstreetmap.de/changeset/16799/josm
images/preference is the replacement

### CODE REVIEW

**Comment by Klumbumbus** [comment]
Could someone please merge this PR and release 0.6.6?

**Comment by Klumbumbus** [comment]
https://josm.openstreetmap.de/ticket/19592

**Comment by Klumbumbus** [comment]
Could you do the release too pls?

**Comment by simon04** [comment]
https://github.com/JOSM/conflation/releases/tag/v0.6.6

Hopefully I did it right. Nowadays, every plugin is built and released differently.

**Comment by Klumbumbus** [comment]
I think so. After I activated it in the preferences JOSM says:

Could not load plugin 'jts' because the plugin main class 'org.openstreetmap.josm.plugins.jts.JTSPlugin' was not found. Delete from preferences?

But that seems unrelated and after a JOSM restart the conflation panel is available.

**Comment by Klumbumbus** [comment]
https://josm.openstreetmap.de/wiki/PluginsSource?action=diff&version=546

**Pull request merged**
