### PR TITLE
Add a merge NOT tags entry

### PR DESCRIPTION
**Pull request by bagage**
capture d ecran de 2017-04-01 16-34-39

### CODE REVIEW

**Comment by tyndare** [comment]
I like the idea of your proposition, I have one comment and one issue:

- I think it would make it even more clear if you could add a new label named "except" between the 2 text box.

- The ALL Collection was an immutable singleton constant. You made it mutable but it's still a singleton, so if you modify it, this singleton will not represent ALL anymore... I think you should make it a named class, and instantiate it each time instead of using it as a singleton constant.

**Comment by tyndare** [comment]
I'll integrate it and make the modifications I mentioned.

**Comment by bagage** [comment]
Well I have additional changes actually I can do another OR this afternoon.

**Comment by tyndare** [comment]
Ok, please do a git pull before, I've just made some refactoring that could impact what you are doing:
https://github.com/JOSM/conflation/commit/6ad0264b894bac672af18db9e0cd6ca48428256b

**Pull request merged**
